spring:
  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG