spring:
  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true

wallet:
  retry:
    max-attempts: ${WALLET_RETRY_MAX_ATTEMPTS:5}
    delay: ${WALLET_RETRY_DELAY:50}
    multiplier: ${WALLET_RETRY_MULTIPLIER:2}
